version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matching_system
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/matching_system}
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}
      - JWT_SECRET=${JWT_SECRET:-secret}
    ports:
      - "${PORT:-5000}:5000"
    depends_on:
      - mongo

volumes:
  mongo-data:
